#! /bin/bash

######################################
# THIS IS A WORK IN PROGRESS SCRIPT. #
#                                    #
#                                    #
#                                    #
######################################


## The scope of this script is create 
## Data Lake Structure
##
##

# The timestamp of the process that ran this
TIMESTAMP=`date +%Y%m%d%H%M%S%N`

LOG_FILE="data_lake_creation_"$TIMESTAMP".log"
ROOT="SDP"
RUN_AS_USER="hdfs"

function usage {
cat <<EOF
$0 [<options>] [<application arguments>]
Both the long and short options should be separated from their argument by "=", eg. "--environment=DEV" or "-e=DEV".
Please edit "$0" if you want to change the default values.

Note: One of the following options have no default values and should be specified:
  --environment, --run-as-user

General Options:
  --help               | -h   : Show this guide and exit.

Application Options:
  --environment=x     | -e=x : the 3 letter environment code; e.g. DEV, SIT, PRD
  --run-as-user=x  | -ru=x : the user must a valid user
 

Examples:
  $0 --environment="DEV" --run-as-user="hdfs" 
  $0 --environment="DEV" --run-as-user="hdfs"

EOF
}


function checkParameters {
  # Check if the country code parameters is defined
  if [ -z "$ENV" ]; then usage; exit -1; fi
  # Check if the country code parameters is defined
#  if [ -z "$VALID_FROM_DATE" ]; then usage; exit -1; fi
  # Check if help was requested 
#  if [ ! -z "$SHOW_HELP" ]; then usage; exit -1; fi
}

#################################
# Main
#################################

# Parse options.
# Note: Not in standard POSIX or GNU format, but easier to parse in sh.
#   For options with argument, "=" is always required.
for i in "$@"
do
  case $i in
    --help|-h) SHOW_HELP=true; break;;
    --environment=*|-e=*) ENV="${i#*=}";;
    --run-as-user=*|-ru=*) RUN_AS_USER="${i#*=}";;
    --) shift; break;;
    -*) echo "Unrecognized option $i."; SHOW_HELP=true; break;;
    *) break;; # Other arguments will be passed as is to spark-submit, appended to the end of application parameters.
  esac
  shift # skip parsed options
done

checkParameters

#################################
# PREPARATIONS
#################################
SOURCE_LZ=("AM-HELIOS" "AMS-DAWN" "AMS-LOG" "RENG" "TVA" "CASIS" "VOD" "APP_METRICS" "CAS"  "CONVIVA")
CMD_PREFIX="sudo -u "$RUN_AS_USER 

#################################
# DATA LAKE CREATION
#################################

### Framework folder creation ###

$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/APPS/FRAMEWORK/BIN
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/APPS/FRAMEWORK/OOZIE
echo "/$ROOT/$ENV/APPS/FRAMEWORK/ folders created" >> $LOG_FILE 2>&1
$CMD_PREFIX hdfs dfs -ls  /$ROOT/$ENV/APPS/FRAMEWORK/ >> $LOG_FILE 2>&1

### Application name folder creation ###
CONSUMER_APP="AUDIENCE_MEASUREMENTS"
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/APPS/$CONSUMER_APP/BIN
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/APPS/$CONSUMER_APP/OOZIE
echo "$ROOT/$ENV/APPS/$CONSUMER_APP folders created" >> $LOG_FILE 2>&1
$CMD_PREFIX hdfs dfs -ls  /$ROOT/$ENV/APPS/$CONSUMER_APP >> $LOG_FILE 2>&1

### Create LZ & CDL folders ###
LAYER_ARRAY=("LANDING_ZONE" "CURATED_DATALAKE")
for LAYER in "${LAYER_ARRAY[@]}"
do
   case $LAYER in
    LANDING_ZONE) SUFFIX_ARR=("/INBOX" "/ERROR" "/ARCHIVE");;
    CURATED_DATALAKE) SUFFIX_ARR=("");;
   esac
   for SUFFIX in "${SUFFIX_ARR[@]}"
   do
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AM-HELIOS/CZ$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AM-HELIOS/HU$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AM-HELIOS/RO$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AM-HELIOS/SK$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-DAWN/AT$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-DAWN/CZ$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-DAWN/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-LOG/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-LOG/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/AMS-LOG/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/RENG/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/RENG/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/RENG/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/RENG/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/CZ$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/DE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/AT$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/TVA/HU$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CASIS/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CASIS/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CASIS/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/DE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/AT$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/VOD/HU$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/AT$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/IE$SUFFIX 
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/CZ$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/HU$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/APP_METRICS/DE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CAS/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CAS/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CAS/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/IE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/NL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/CZ$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/UK$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/CONVIVA/PL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/EOS/BE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/EOS/CH$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/EOS/CL$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/EOS/DE$SUFFIX
		$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/EOS/NL$SUFFIX
	done
	### Check LZ&CURATED folder ###
	for j in "${SOURCE_LZ[@]}"
	do
		echo "$LAYER source $j folder created" >> $LOG_FILE 2>&1
		$CMD_PREFIX hdfs dfs -ls /$ROOT/$ENV/DATA_LAKE/$LAYER/NLECXUDTGW01/$j >> $LOG_FILE 2>&1
	done
done 
### Create CDL TVA SPECIF folders ###
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CH/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/CZ/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/IE/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/NL/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/PL/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/DE/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/AT/CLASSIFICATIONSCHEME
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/PROGRAMINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/GROUPINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/SCHEDULE
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/BROADCASTEVENT
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/ONDEMANDPROGRAM
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/SERVICEINFORMATION
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/RATING
$CMD_PREFIX hdfs dfs -mkdir -p /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/HU/CLASSIFICATIONSCHEME

COUNTRY_TVA=("AT" "CH" "CZ" "IE" "NL" "PL" "DE" "HU")
for k in "${COUNTRY_TVA[@]}"
	do
		echo "Curated Datalake folder for TVA Country $k created" >> $LOG_FILE 2>&1
		$CMD_PREFIX hdfs dfs -ls /$ROOT/$ENV/DATA_LAKE/CURATED_DATALAKE/NLECXUDTGW01/TVA/$k >> $LOG_FILE 2>&1
	done 